# Evaluate if a number is even or odd
number = int(input("Enter any number: "))
if number % 2 != 0:
    print("{} is an odd number".format(number))
else:
    print("{} is an even number".format(number))
#using random int
import random
random_num = random.randint(0, 1000)
if random_num % 2 != 0:
    print("{} has been generated by the system, and is and odd number".format(random_num))
else:
    print("{} has been generated by the system, and is an even number".format(random_num))